In [1]:
#pip install boto3 pyarrow

In [2]:
# best security practice to avoid hard-coding access credentials
with open('/opt/app-root/src/s3-auth.txt', 'r') as file:
    lines = [line.rstrip() for line in file.readlines()]

s3_endpoint_url = lines[0]
s3_access_key = lines[1]
s3_secret_key = lines[2]
s3_bucket = lines[3]
del lines

[s3_endpoint_url, s3_bucket]

['https://s3.us-east-1.amazonaws.com', 'ocp-odh-os-demo-s3']

In [3]:
with open('/opt/app-root/src/trino-auth.txt', 'r') as file:
    lines = [line.rstrip() for line in file.readlines()]

trino_user = lines[0]
trino_passwd = lines[1]
trino_host = 'trino-secure-odh-trino.apps.odh-cl1.apps.os-climate.org'
trino_port = 443
del lines

trino_user

'erik'

In [4]:
import boto3
# Create an S3 client
s3 = boto3.client(
    service_name="s3",
    aws_access_key_id=s3_access_key,
    aws_secret_access_key=s3_secret_key,
    endpoint_url=s3_endpoint_url,
)

In [5]:
import pandas as pd
obj = s3.get_object(
    Bucket=s3_bucket,
    Key='urgentem/UrgentemDataSampleDec2020.csv')
dfSample = (pd.read_csv(obj['Body'])).convert_dtypes()
dfSample.head()

,Company (Short) Name,ISIN,SEDOL,Bloomberg Ticker,Urgentem Disclosure Category,Number of Scope 3 Categories Disclosed,Country,Region,"Intensity Average Inference Scope 1, 2 & 3 Total (tCO2e/$m Revenue)",Intensity Average Inference Scope 1 & 2 Total (tCO2e/$m Revenue),...,Maximum Emissions Absolute - Scope 3 Business Travel (tCO2e),Maximum Emissions Absolute - Scope 3 Employee Commuting (tCO2e),Maximum Emissions Absolute - Scope 3 Upstream Leased Assets (tCO2e),Maximum Emissions Absolute - Scope 3 Downstream Transport Distribution (tCO2e),Maximum Emissions Absolute - Scope 3 Processing of Sold Products (tCO2e),Maximum Emissions Absolute - Scope 3 Use of Sold Products (tCO2e),Maximum Emissions Absolute - Scope 3 End of Life Treatment of Sold Products (tCO2e),Maximum Emissions Absolute - Scope 3 Downstream Leased Assets (tCO2e),Maximum Emissions Absolute - Scope 3 Franchises (tCO2e),Maximum Emissions Absolute - Scope 3 Investments (tCO2e)
0,3M CO,US88579Y1010,2595708,MMM US,2,8,United States,North America,1441.1,191.0,...,"61,600","327,000","1,108,199","7,967,995","17,111,606","1,182,365,223","11,967,309","1,000","546,481","65,016,450"
1,ADIDAS AG,DE000A1EWWW0,4031976,ADS GR,3,3,Germany,Europe,301.0,17.5,...,"100,504","503,985","138,714","4,889,501","1,057,851","763,535,408","6,659,128","1,684,272","2,887,171","1,554,673"
2,ALPHABET INC-A,US02079K3059,BYVY8G0,GOOGL US,1,9,United States,North America,218.0,6.0,...,"313,000","150,467","5,499,320","5,510","17,319,081","518,414,903",241,"6,025,821","291,674","13,365,613"
3,BANCO SANTANDER,ES0113900J37,5705946,SAN SM,1,2,Spain,Europe,693.1,4.1,...,"75,524","780,738","261,880","4,029,102","253,176","20,786","611,505","209,031","703,165","807,902,287"
4,BARCLAYS PLC,GB0031348658,3134865,BARC LN,1,3,United Kingdom,Europe,709.2,9.7,...,"69,233","352,851","118,355","1,820,934","114,422","9,394","276,367","94,471","317,792","365,127,757"

In [6]:
dfSample.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 172 columns):
 #    Column                                                                                                  Dtype
---   ------                                                                                                  -----
 0    Company (Short) Name                                                                                    string
 1    ISIN                                                                                                    string
 2    SEDOL                                                                                                   string
 3    Bloomberg Ticker                                                                                        string
 4    Urgentem Disclosure Category                                                                            Int64
 5    Number of Scope 3 Categories Disclosed                                                                  Int64
 6    Country                                                                                                 string
 7    Region                                                                                                  string
 8    Intensity Average Inference Scope 1, 2 & 3 Total (tCO2e/$m Revenue)                                     Float64
 9    Intensity Average Inference Scope 1 & 2 Total (tCO2e/$m Revenue)                                        Float64
 10   Intensity Average Inference Scope 1 & 2 Total (tCO2e/$m Revenue) - Source                               string
 11   Intensity Average Inference Scope 3 Total (tCO2e/$m Revenue)                                            Float64
 12   Intensity Average Inference Scope 3 Total (tCO2e/$m Revenue) - Source                                   string
 13   Intensity Average Inference Scope 1 (tCO2e/$m Revenue)                                                  Float64
 14   Intensity Average Inference Scope 1 (tCO2e/$m Revenue) - Source                                         string
 15   Intensity Average Inference Scope 2 Location Based (tCO2e/$m Revenue)                                   Float64
 16   Intensity Average Inference Scope 2 Location Based (tCO2e/$m Revenue) - Source                          string
 17   Intensity Average Inference Scope 2 Market Based (tCO2e/$m Revenue)                                     Float64
 18   Intensity Average Inference Scope 2 Market Based (tCO2e/$m Revenue) - Source                            string
 19   Intensity Average Inference Scope 3 Purchased Goods and Services (tCO2e/$m Revenue)                     Float64
 20   Intensity Average Inference Scope 3 Purchased Goods and Services (tCO2e/$m Revenue) - Source            string
 21   Intensity Average Inference Scope 3 Capital Goods (tCO2e/$m Revenue)                                    Float64
 22   Intensity Average Inference Scope 3 Capital Goods (tCO2e/$m Revenue) - Source                           string
 23   Intensity Average Inference Scope 3 Fuel and Energy Related Activities (tCO2e/$m Revenue)               Float64
 24   Intensity Average Inference Scope 3 Fuel and Energy Related Activities (tCO2e/$m Revenue) - Source      string
 25   Intensity Average Inference Scope 3 Upstream Transport and Distribution (tCO2e/$m Revenue)              Float64
 26   Intensity Average Inference Scope 3 Upstream Transport and Distribution (tCO2e/$m Revenue) - Source     string
 27   Intensity Average Inference Scope 3 Waste Generated (tCO2e/$m Revenue)                                  Float64
 28   Intensity Average Inference Scope 3 Waste Generated (tCO2e/$m Revenue) - Source                         string
 29   Intensity Average Inference Scope 3 Business Travel (tCO2e/$m Revenue)                                  Float64
 30   Intensity Average Inference Scope 3 Business Travel (tCO2e/$m Revenue) - Source                         string
 31   Intensity Average Inference Scope 3 Employee Commuting (tCO2e/$m Revenue)                               Float64
 32   Intensity Average Inference Scope 3 Employee Commuting (tCO2e/$m Revenue) - Source                      string
 33   Intensity Average Inference Scope 3 Upstream Leased Assets (tCO2e/$m Revenue)                           Float64
 34   Intensity Average Inference Scope 3 Upstream Leased Assets (tCO2e/$m Revenue) - Source                  string
 35   Intensity Average Inference Scope 3 Downstream Transport Distribution (tCO2e/$m Revenue)                Float64
 36   Intensity Average Inference Scope 3 Downstream Transport Distribution (tCO2e/$m Revenue) - Source       string
 37   Intensity Average Inference Scope 3 Processing of Sold Products (tCO2e/$m Revenue)                      Float64
 38   Intensity Average Inference Scope 3 Processing of Sold Products (tCO2e/$m Revenue) - Source             string
 39   Intensity Average Inference Scope 3 Use of Sold Products (tCO2e/$m Revenue)                             Float64
 40   Intensity Average Inference Scope 3 Use of Sold Products (tCO2e/$m Revenue) - Source                    string
 41   Intensity Average Inference Scope 3 End of Life Treatment of Sold Products (tCO2e/$m Revenue)           Float64
 42   Intensity Average Inference Scope 3 End of Life Treatment of Sold Products (tCO2e/$m Revenue) - Source  string
 43   Intensity Average Inference Scope 3 Downstream Leased Assets (tCO2e/$m Revenue)                         Float64
 44   Intensity Average Inference Scope 3 Downstream Leased Assets (tCO2e/$m Revenue) - Source                string
 45   Intensity Average Inference Scope 3 Franchises (tCO2e/$m Revenue)                                       Float64
 46   Intensity Average Inference Scope 3 Franchises (tCO2e/$m Revenue) - Source                              string
 47   Intensity Average Inference Scope 3 Investments (tCO2e/$m Revenue)                                      Float64
 48   Intensity Average Inference Scope 3 Investments (tCO2e/$m Revenue) - Source                             string
 49   Maximum Emissions Intensity Scope 1, 2 & 3 (tCO2e/$m Revenue)                                           Float64
 50   Maximum Emissions Intensity Scope 1 & 2 (tCO2e/$m Revenue)                                              Float64
 51   Maximum Emissions Intensity Scope 1 & 2 (tCO2e/$m Revenue) - Source                                     string
 52   Maximum Emissions Intensity Scope 3 Total (tCO2e/$m Revenue)                                            Float64
 53   Maximum Emissions Intensity Scope 3 (tCO2e/$m Revenue) - Source                                         string
 54   Maximum Emissions Intensity Scope 1 (tCO2e/$m Revenue)                                                  Float64
 55   Maximum Emissions Intensity Scope 1 (tCO2e/$m Revenue) - Source                                         string
 56   Maximum Emissions Intensity Scope 2 Location Based (tCO2e/$m Revenue)                                   Float64
 57   Maximum Emissions Intensity Scope 2 Location Based (tCO2e/$m Revenue) - Source                          string
 58   Maximum Emissions Intensity Scope 2 Market Based (tCO2e/$m Revenue)                                     Float64
 59   Maximum Emissions Intensity Scope 2 Market Based (tCO2e/$m Revenue) - Source                            string
 60   Maximum Emissions Intensity Scope 3 Purchased Goods and Services (tCO2e/$m Revenue)                     Float64
 61   Maximum Emissions Intensity Scope 3 Purchased Goods and Services (tCO2e/$m Revenue) - Source            string
 62   Maximum Emissions Intensity Scope 3 Capital Goods (tCO2e/$m Revenue)                                    Float64
 63   Maximum Emissions Intensity Scope 3 Capital Goods (tCO2e/$m Revenue) - Source                           string
 64   Maximum Emissions Intensity Scope 3 Fuel and Energy Related Activities (tCO2e/$m Revenue)               Float64
 65   Maximum Emissions Intensity Scope 3 Fuel and Energy Related Activities (tCO2e/$m Revenue) - Source      string
 66   Maximum Emissions Intensity Scope 3 Upstream Transport and Distribution (tCO2e/$m Revenue)              Float64
 67   Maximum Emissions Intensity Scope 3 Upstream Transport and Distribution (tCO2e/$m Revenue) - Source     string
 68   Maximum Emissions Intensity Scope 3 Waste Generated (tCO2e/$m Revenue)                                  Float64
 69   Maximum Emissions Intensity Scope 3 Waste Generated (tCO2e/$m Revenue) - Source                         string
 70   Maximum Emissions Intensity Scope 3 Business Travel (tCO2e/$m Revenue)                                  Float64
 71   Maximum Emissions Intensity Scope 3 Business Travel (tCO2e/$m Revenue) - Source                         string
 72   Maximum Emissions Intensity Scope 3 Employee Commuting (tCO2e/$m Revenue)                               Float64
 73   Maximum Emissions Intensity Scope 3 Employee Commuting (tCO2e/$m Revenue) - Source                      string
 74   Maximum Emissions Intensity Scope 3 Upstream Leased Assets (tCO2e/$m Revenue)                           Float64
 75   Maximum Emissions Intensity Scope 3 Upstream Leased Assets (tCO2e/$m Revenue) - Source                  string
 76   Maximum Emissions Intensity Scope 3 Downstream Transport Distribution (tCO2e/$m Revenue)                Float64
 77   Maximum Emissions Intensity Scope 3 Downstream Transport Distribution (tCO2e/$m Revenue) - Source       string
 78   Maximum Emissions Intensity Scope 3 Processing of Sold Products (tCO2e/$m Revenue)                      Float64
 79   Maximum Emissions Intensity Scope 3 Processing of Sold Products (tCO2e/$m Revenue) - Source             string
 80   Maximum Emissions Intensity Scope 3 Use of Sold Products (tCO2e/$m Revenue)                             Float64
 81   Maximum Emissions Intensity Scope 3 Use of Sold Products (tCO2e/$m Revenue) - Source                    string
 82   Maximum Emissions Intensity Scope 3 End of Life Treatment of Sold Products (tCO2e/$m Revenue)           Float64
 83   Maximum Emissions Intensity Scope 3 End of Life Treatment of Sold Products (tCO2e/$m Revenue) - Source  string
 84   Maximum Emissions Intensity Scope 3 Downstream Leased Assets (tCO2e/$m Revenue)                         Float64
 85   Maximum Emissions Intensity Scope 3 Downstream Leased Assets (tCO2e/$m Revenue) - Source                string
 86   Maximum Emissions Intensity Scope 3 Franchises (tCO2e/$m Revenue)                                       Float64
 87   Maximum Emissions Intensity Scope 3 Franchises (tCO2e/$m Revenue) - Source                              string
 88   Maximum Emissions Intensity Scope 3 Investments (tCO2e/$m Revenue)                                      Float64
 89   Maximum Emissions Intensity Scope 3 Investments (tCO2e/$m Revenue) - Source                             string
 90   Reported Emissions Intensity Scope 1 & 2 (tCO2e/$m Revenue)                                             Float64
 91   Reported Emissions Intensity Scope 1 Gross (tCO2e/$m Revenue)                                           Float64
 92   Reported Emissions Intensity Scope 2 Location based (tCO2e/$m Revenue)                                  Float64
 93   Reported Emissions Intensity Scope 2 Market based (tCO2e/$m Revenue)                                    Float64
 94   Reported Emissions Intensity Scope 3 (tCO2e/$m Revenue)                                                 Float64
 95   Reported Emissions Intensity Scope 3 1. Purchased Goods and Services (tCO2e/$m Revenue)                 Float64
 96   Reported Emissions Intensity Scope 3 2. Capital Goods (tCO2e/$m Revenue)                                Float64
 97   Reported Emissions Intensity Scope 3 3. Fuel and Energy Related Activities (tCO2e/$m Revenue)           Float64
 98   Reported Emissions Intensity Scope 3 4. Upstream Transportation (tCO2e/$m Revenue)                      Float64
 99   Reported Emissions Intensity Scope 3 5. Waste Generated in Operations (tCO2e/$m Revenue)                Float64
 100  Reported Emissions Intensity Scope 3 6. Business Travel (tCO2e/$m Revenue)                              Float64
 101  Reported Emissions Intensity Scope 3 7. Employee Commuting (tCO2e/$m Revenue)                           Float64
 102  Reported Emissions Intensity Scope 3 8. Upstream Leased Assets (tCO2e/$m Revenue)                       Float64
 103  Reported Emissions Intensity Scope 3 9. Downstream Transportation (tCO2e/$m Revenue)                    Float64
 104  Reported Emissions Intensity Scope 3 10. Processing of Sold Products (tCO2e/$m Revenue)                 Float64
 105  Reported Emissions Intensity Scope 3 11. Use of Sold Products (tCO2e/$m Revenue)                        Float64
 106  Reported Emissions Intensity Scope 3 12. End of Life Treatment of Sold Products (tCO2e/$m Revenue)      Float64
 107  Reported Emissions Intensity Scope 3 13. Downstream Leased Assets (tCO2e/$m Revenue)                    Float64
 108  Reported Emissions Intensity Scope 3 14. Franchises (tCO2e/$m Revenue)                                  Float64
 109  Reported Emissions Intensity Scope 3 15. Investments (tCO2e/$m Revenue)                                 Float64
 110  Reported Emissions Total Scope 1 & 2 (tCO2e)                                                            string
 111  Reported Emissions Total Scope 3 (tCO2e)                                                                string
 112  Reported Emissions Scope 1 Gross (tCO2e)                                                                string
 113  Reported Emissions Scope 2 Location based (tCO2e)                                                       string
 114  Reported Emissions Scope 2 Market based (tCO2e)                                                         string
 115  Reported Emissions Scope 3 1. Purchased Goods and Services (tCO2e)                                      string
 116  Reported Emissions Scope 3 2. Capital Goods (tCO2e)                                                     string
 117  Reported Emissions Scope 3 3. Fuel and Energy Related Activities (tCO2e)                                string
 118  Reported Emissions Scope 3 4. Upstream Transportation (tCO2e)                                           string
 119  Reported Emissions Scope 3 5. Waste Generated in Operations (tCO2e)                                     string
 120  Reported Emissions Scope 3 6. Business Travel (tCO2e)                                                   string
 121  Reported Emissions Scope 3 7. Employee Commuting (tCO2e)                                                string
 122  Reported Emissions Scope 3 8. Upstream Leased Assets (tCO2e)                                            string
 123  Reported Emissions Scope 3 9. Downstream Transportation (tCO2e)                                         string
 124  Reported Emissions Scope 3 10. Processing of Sold Products (tCO2e)                                      string
 125  Reported Emissions Scope 3 11. Use of Sold Products (tCO2e)                                             string
 126  Reported Emissions Scope 3 12. End of Life Treatment of Sold Products (tCO2e)                           string
 127  Reported Emissions Scope 3 13. Downstream Leased Assets (tCO2e)                                         string
 128  Reported Emissions Scope 3 14. Franchises (tCO2e)                                                       string
 129  Reported Emissions Scope 3 15. Investments (tCO2e)                                                      string
 130  Absolute - Average Inference Scope 1, 2 & 3 Total (tCO2e)                                               string
 131  Absolute - Average Inference Scope 1 & 2 Total (tCO2e)                                                  string
 132  Absolute - Average Inference Scope 3 Total (tCO2e)                                                      string
 133  Absolute - Average Inference Scope 1 (tCO2e)                                                            string
 134  Absolute - Average Inference Scope 2 Location Based (tCO2e)                                             string
 135  Absolute - Average Inference Scope 2 Market Based (tCO2e)                                               string
 136  Absolute - Average Inference Scope 3 Purchased Goods and Services (tCO2e)                               string
 137  Absolute - Average Inference Scope 3 Capital Goods (tCO2e)                                              string
 138  Absolute - Average Inference Scope 3 Fuel and Energy Related Activities (tCO2e)                         string
 139  Absolute - Average Inference Scope 3 Upstream Transport and Distribution (tCO2e)                        string
 140  Absolute - Average Inference Scope 3 Waste Generated (tCO2e)                                            string
 141  Absolute - Average Inference Scope 3 Business Travel (tCO2e)                                            string
 142  Absolute - Average Inference Scope 3 Employee Commuting (tCO2e)                                         string
 143  Absolute - Average Inference Scope 3 Upstream Leased Assets (tCO2e)                                     string
 144  Absolute - Average Inference Scope 3 Downstream Transport Distribution (tCO2e)                          string
 145  Absolute - Average Inference Scope 3 Processing of Sold Products (tCO2e)                                string
 146  Absolute - Average Inference Scope 3 Use of Sold Products (tCO2e)                                       string
 147  Absolute - Average Inference Scope 3 End of Life Treatment of Sold Products (tCO2e)                     string
 148  Absolute - Average Inference Scope 3 Downstream Leased Assets (tCO2e)                                   string
 149  Absolute - Average Inference Scope 3 Franchises (tCO2e)                                                 string
 150  Absolute - Average Inference Scope 3 Investments (tCO2e)                                                string
 151  Maximum Emissions Absolute - Scope 1, 2 & 3 (tCO2e)                                                     string
 152  Maximum Emissions Absolute - Scope 1 & 2 (tCO2e)                                                        string
 153  Maximum Emissions Absolute - Scope 3 Total (tCO2e)                                                      string
 154  Maximum Emissions Absolute - Scope 1 (tCO2e)                                                            string
 155  Maximum Emissions Absolute - Scope 2 Location Based (tCO2e)                                             string
 156  Maximum Emissions Absolute - Scope 2 Market Based (tCO2e)                                               string
 157  Maximum Emissions Absolute - Scope 3 Purchased Goods and Services (tCO2e)                               string
 158  Maximum Emissions Absolute - Scope 3 Capital Goods (tCO2e)                                              string
 159  Maximum Emissions Absolute - Scope 3 Fuel and Energy Related Activities (tCO2e)                         string
 160  Maximum Emissions Absolute - Scope 3 Upstream Transport and Distribution (tCO2e)                        string
 161  Maximum Emissions Absolute - Scope 3 Waste Generated (tCO2e)                                            string
 162  Maximum Emissions Absolute - Scope 3 Business Travel (tCO2e)                                            string
 163  Maximum Emissions Absolute - Scope 3 Employee Commuting (tCO2e)                                         string
 164  Maximum Emissions Absolute - Scope 3 Upstream Leased Assets (tCO2e)                                     string
 165  Maximum Emissions Absolute - Scope 3 Downstream Transport Distribution (tCO2e)                          string
 166  Maximum Emissions Absolute - Scope 3 Processing of Sold Products (tCO2e)                                string

In [7]:
obj = s3.get_object(
    Bucket=s3_bucket,
    Key='urgentem/UrgentemDataSampleEmissionsTargetsDec2020.csv')
dfEmissions = (pd.read_csv(obj['Body'])).convert_dtypes()
dfEmissions.head()

,Company Name,ISIN,Target Type,Scope,Coverage - S1,Coverage - S2,Coverage - S3,Reduction Ambition,Base Year,End Year,Start Year,Base Year GHG Emissions S1 (tCO2e),Base Year GHG Emissions S1+S2 (tCO2e),Base Year GHG Emissions S3 (tCO2e),Achieved Reduction
0,3M CO,US88579Y1010,Absolute,S1+S2,1.0,1.0,<NA>,0.5,2002,2025,2015,<NA>,"18,300,000","91,500,000",0.3
1,ADIDAS AG,DE000A1EWWW0,Absolute,S1+S2,0.9,0.9,<NA>,0.15,2015,2020,2015,<NA>,"59,132","295,660",1.0
2,BARCLAYS PLC,GB0031348658,Absolute,S1+S2,1.0,1.0,<NA>,0.37,2018,2025,2018,<NA>,"282,593","1,412,965",0.0
3,DANONE,FR0000120644,Absolute,S1+S2,0.95,0.95,<NA>,0.3,2015,2030,2017,<NA>,"1,681,235","8,406,175",0.68
4,EQUINOR ASA,NO0010096985,Absolute,S1,1.0,<NA>,<NA>,0.21,2016,2030,2017,"9,329,201",<NA>,<NA>,0.06

In [8]:
dfEmissions.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 15 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Company Name                           19 non-null     string
 1   ISIN                                   19 non-null     string
 2   Target Type                            19 non-null     string
 3   Scope                                  19 non-null     string
 4   Coverage - S1                          16 non-null     Float64
 5   Coverage - S2                          15 non-null     Float64
 6   Coverage - S3                          4 non-null      Int64
 7   Reduction Ambition                     19 non-null     Float64
 8   Base Year                              19 non-null     Int64
 9   End Year                               19 non-null     Int64
 10  Start Year                             19 non-null     Int64
 11  Base Year GHG Emissions S1 (tCO2e)     1 non-null      string
 12  Base Year GHG Emissions S1+S2 (tCO2e)  14 non-null     string
 13  Base Year GHG Emissions S3 (tCO2e)     18 non-null     string
 14  Achieved Reduction                     19 non-null     Float64
dtypes: Float64(4), Int64(4), string(7)
memory usage: 2.5 KB

In [9]:
dfEmissions.columns.to_list()

['Company Name',
 'ISIN',
 'Target Type',
 'Scope',
 'Coverage - S1',
 'Coverage - S2',
 'Coverage - S3',
 'Reduction Ambition',
 'Base Year',
 'End Year',
 'Start Year',
 'Base Year GHG Emissions S1 (tCO2e)',
 'Base Year GHG Emissions S1+S2 (tCO2e)',
 'Base Year GHG Emissions S3 (tCO2e)',
 'Achieved Reduction']

In [10]:
rename_map = dict(list(zip(dfEmissions.columns.to_list(),[
    'company_name',
    'isin',
    'target_type',
    'scope',
    'coverage_s1',
    'coverage_s2',
    'coverage_s3',
    'reduction_ambition',
    'base_year',
    'end_year',
    'start_year',
    'base_year_ghg_emissions_s1',
    'base_year_ghg_emissions_s1_s2',
    'base_year_ghg_emissions_s3',
    'achieved_reduction'
])))
dfEmissions.rename(columns=rename_map, inplace=True)

In [11]:
dfEmissions.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company_name                   19 non-null     string
 1   isin                           19 non-null     string
 2   target_type                    19 non-null     string
 3   scope                          19 non-null     string
 4   coverage_s1                    16 non-null     Float64
 5   coverage_s2                    15 non-null     Float64
 6   coverage_s3                    4 non-null      Int64
 7   reduction_ambition             19 non-null     Float64
 8   base_year                      19 non-null     Int64
 9   end_year                       19 non-null     Int64
 10  start_year                     19 non-null     Int64
 11  base_year_ghg_emissions_s1     1 non-null      string
 12  base_year_ghg_emissions_s1_s2  14 non-null     string
 13  base_year_ghg_emissions_s3     18 non-null     string
 14  achieved_reduction             19 non-null     Float64
dtypes: Float64(4), Int64(4), string(7)
memory usage: 2.5 KB

In [12]:
# parquet has multiple options for appending or updating data
# including adding new files, or appending, sharding directory trees, etc
dfEmissions.to_parquet('/tmp/emissions.parquet', index=False)
s3.upload_file(
    Bucket=s3_bucket,
    Key='urgentem/trino/itr_emissions_sample/emissions.parquet',
    Filename='/tmp/emissions.parquet'
)

In [13]:
import trino
conn = trino.dbapi.connect(
    auth=trino.auth.BasicAuthentication(trino_user, trino_passwd),
    host=trino_host,
    port=trino_port,
    http_scheme='https',
    verify=False,
)
cur = conn.cursor()

In [14]:
# this does not work, need to research why
result = cur.execute(
"""create table if not exists hive.urgentem.itr_emissions_sample(
    company_name varchar,
    isin varchar,
    target_type varchar,
    scope varchar,
    coverage_s1 double,
    coverage_s2 double,
    coverage_s3 bigint,
    reduction_ambition double,
    base_year bigint,
    end_year bigint,
    start_year bigint,
    base_year_ghg_emissions_s1 varchar,
    base_year_ghg_emissions_s1_s2 varchar,
    base_year_ghg_emissions_s3 varchar,
    achieved_reduction double
) with (
    format = 'parquet',
    external_location = 's3a://ocp-odh-os-demo-s3/urgentem/trino/itr_emissions_sample/'
)"""
)

/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'trino-secure-odh-trino.apps.odh-cl1.apps.os-climate.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(